spring:
  datasource:
    card:
      username: carduser
      password: password
      url: jdbc:mysql://127.0.0.1:3306/card?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      flyway:
        username: cardadmin
        password: password
        url: jdbc:mysql://127.0.0.1:3306/card?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      hikari:
        poolName: HikariPool-Card
    cardholder:
      username: cardholderuser
      password: password
      url: jdbc:mysql://127.0.0.1:3306/cardholder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      flyway:
        username: cardholderadmin
        password: password
        url: jdbc:mysql://127.0.0.1:3306/cardholder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      hikari:
        poolName: HikariPool-CardHolder
    pan:
      username: panuser
      password: password
      url: jdbc:mysql://127.0.0.1:3306/pan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      flyway:
        username: panadmin
        password: password
        url: jdbc:mysql://127.0.0.1:3306/pan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      hikari:
        poolName: HikariPool-Pan